
//Proyecto Final
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import static java.awt.SystemColor.text;
import static java.lang.reflect.Array.set;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class Excepcion extends javax.swing.JFrame {
    
    /**
     * Creates new form Excepcion
     */
    ImagenFondo excepcion = new ImagenFondo();
    public Excepcion(String s) {
        this.setTitle("ERROR");
        this.setContentPane(excepcion);
        initComponents(s);
        this.setLocationRelativeTo(Excepcion.this);
        setSize(250,150);
        setIconImage(new ImageIcon(getClass().getResource("error.png")).getImage());
      
    }
    
    private void initComponents(String s) {
        float[] floats = new float[3];

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setLabelFor(this);
        jLabel1.setText(s);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(8, 57, 500, 40);
        jLabel1.setFont(new Font("Candara Bold",1,15));
        Color.RGBtoHSB(53, 160, 232, floats);
        jLabel1.setForeground(Color.getHSBColor(floats[0], floats[1], floats[2]));
        pack();
    }
    private Excepcion() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setText(s);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 140, 34, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
 
    class ImagenFondo extends JLabel{
        private Image imagen;
        
        public void paint (Graphics g){
            imagen = new ImageIcon(getClass().getResource("excepcion.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
}

